fe_general:
    resource: "@FEGeneralBundle/Resources/config/routing.yml"
    prefix:   /

fe_favoris:
    resource: "@FEFavorisBundle/Resources/config/routing.yml"
    prefix:   /

fe_account:
    resource: "@FEAccountBundle/Resources/config/routing.yml"
    prefix:   /
